### ISSUE TITLE
Suggestion for previous bot

### ISSUE THREAD

**Issue by timobolb-man** [nextcord/previous#91]
a who closed ur thread message when ur thread gets closed
Plus a reason when you do ?close [reason] or whatever the heck previous prefix is

**Comment by Soheab** [comment]
Can't you just click the link in your dms?

**Comment by koala9712** [comment]
It doesn't say who closed the thread by button
Reason for closing thread, well, it's usually apparent from the chat above if you really want to know about it- else it's rather useless imo.

**Comment by timobolb-man** [comment]
> Can't you just click the link in your dms?

How does that relate? Also mobile moment

**Comment by realShamlol** [comment]
> > Can't you just click the link in your dms?
> 
> How does that relate? Also mobile moment

If you click the link, it will take to your thread and you can see who closed your thread(for whatever reason)

**Comment by TAG-Epic** [comment]
> a who closed ur thread message when ur thread gets closed
This is not necessary. If you think someone mis-used their permissions in order to close your thread when it wasnt done please DM modmail. Please dont attempt to solve the issue yourself. 

> Plus a reason when you do ?close [reason] or whatever the heck previous prefix is
This can already be done and it will be ignored by previous.
